# Resume Configuration
# Simple configuration for resume structure

# Basic Information
name: "Malachi Dunn"
title: "Data Engineer • Data Scientist"
contact:
  email: "malachi@mindwyre.org"
  phone: "(+1) 208-625-1747"
  location: "Oldtown, ID 83822 United States"
  linkedin: "linkedin.com/in/malachidunn"
  github: "github.com/malachi-mindwyre"
  website: "mindwyre.org"

# Section Ordering
section_order:
  - profile
  - education
  - skills
  - experience
  - certifications
  - projects
  - publications

# Custom section titles
section_titles:
  profile: "Profile Summary"
  education: "Education"
  skills: "Technical Skills"
  certifications: "Certifications"
  experience: "Professional Experience"
  projects: "Projects Experience"
  publications: "Publications"